# 0. Install Dependencies and Bring in Data

In [1]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

C:\Users\kkliv\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
df = pd.read_csv(r'E://Toxic Comment Classification//Toxic-Comment-Classification//train.csv//train.csv')

In [3]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\r\nWhy the edits made under my use...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\r\nMore\r\nI can't make any real suggestions...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [4]:
df.tail(20)

id                                       comment_text  \
159551  ffbc2db4225258dd  While about half the references are from BYU-I...   
159552  ffbcd64a71775e04  Prague Spring \r\n\r\nI think that Prague Spri...   
159553  ffbd331a3aa269b9  I see this as having been merged; undoing one ...   
159554  ffbdbb0483ed0841  and i'm going to keep posting the stuff u dele...   
159555  ffc2f409658571f1  "\r\n\r\nHow come when you download that MP3 i...   
159556  ffc671f2acdd80e1  I'll be on IRC, too, if you have a more specif...   
159557  ffc7bbb177c3c966  It is my opinion that that happens to be off-t...   
159558  ffca1e81aefc48ac  Please stop removing content from Wikipedia; i...   
159559  ffca8d71d71a3fae  Image:Barack-obama-mother.jpg listed for delet...   
159560  ffcdcb71854f6d8a  "Editing of article without Consensus & Remova...   
159561  ffd2e85b07b3c7e4  "\r\nNo he did not, read it again (I would hav...   
159562  ffd72e9766c09c97  "\r\n Auto guides and the motoring press are n...   
159563  ffe029a7c79dc7fe  "\r\nplease identify what part of BLP applies ...   
159564  ffe897e7f7182c90  Catalan independentism is the social movement ...   
159565  ffe8b9316245be30  The numbers in parentheses are the additional ...   
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \r\n\r\nThat...   
159568  ffee36eab5c267c9  Spitzer \r\n\r\nUmm, theres no actual article ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\r\nAnd ... I really don't think you understa...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159551      0             0        0       0       0              0  
159552      0             0        0       0       0              0  
159553      0             0        0       0       0              0  
159554      1             0        1       0       1              0  
159555      0             0        0       0       0              0  
159556      0             0        0       0       0              0  
159557      0             0        0       0       0              0  
159558      0             0        0       0       0              0  
159559      0             0        0       0       0              0  
159560      0             0        0       0       0              0  
159561      0             0        0       0       0              0  
159562      0             0        0       0       0              0  
159563      0             0        0       0       0              0  
159564      0             0        0       0       0              0  
159565      0             0        0       0       0              0  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [5]:
df.iloc[9]['comment_text']

'alignment on this subject and which are contrary to those of DuLithgow'

In [6]:
df.iloc[159554]['comment_text']

"and i'm going to keep posting the stuff u deleted until this fucking site closes down have fun u stupid ass bitch don't ever delete anything fuckin hore like i said before go to hell"

In [7]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [8]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [9]:
df[df.columns[2:]].iloc[159554]

toxic            1
severe_toxic     0
obscene          1
threat           0
insult           1
identity_hate    0
Name: 159554, dtype: int64

In [10]:
df[df['identity_hate']==1].head()

id                                       comment_text  \
42   001810bf8c45bf5f  You are gay or antisemmitian? \r\n\r\nArchange...   
105  00472b8e2d38d1ea         A pair of jew-hating weiner nazi schmucks.   
176  006b94add72ed61c  I think that your a Fagget get a oife and burn...   
218  008e0818dde894fb  Kill all niggers. \r\n\r\nI have hard, that ot...   
238  0097dd5c29bf7a15  u r a tw@ fuck off u gay boy.U r smelly.Fuck u...   

     toxic  severe_toxic  obscene  threat  insult  identity_hate  
42       1             0        1       0       1              1  
105      1             0        1       0       1              1  
176      1             0        1       1       1              1  
218      1             0        1       0       1              1  
238      1             0        1       0       1              1

# 1. Preprocess

In [11]:
from tensorflow.keras.layers import TextVectorization

In [12]:
X = df['comment_text']
X

0         Explanation\r\nWhy the edits made under my use...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\r\nMore\r\nI can't make any real suggestions...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \r\n\r\nThat...
159568    Spitzer \r\n\r\nUmm, theres no actual article ...
159569    And it looks like it was actually you who put ...
159570    "\r\nAnd ... I really don't think you understa...
Name: comment_text, Length: 159571, dtype: object

In [13]:
y = df[df.columns[2:]]
y

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [14]:
y = df[df.columns[2:]].values 
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [15]:
MAX_FEATURES = 200000 # number of words in the dictionary --> more words = effective model

In [16]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length=1800,
                               output_mode='int')

In [17]:
vectorizer.adapt(X.values)

In [18]:
type(X)

pandas.core.series.Series

In [19]:
type(X.values)

numpy.ndarray

In [20]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [21]:
vectorizer("Hello, good to be here")[:7]

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([288,  98,   3,  17,  66,   0,   0], dtype=int64)>

In [22]:
vectorized_text = vectorizer(X.values)

In [23]:
vectorized_text  #numeric representation of all the sentences

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [24]:

dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) 

In [25]:
batch_X, batch_y=dataset.as_numpy_iterator().next()

In [26]:
batch_X

array([[  171, 58937,   350, ...,     0,     0,     0],
       [  113,   219,     9, ...,     0,     0,     0],
       [  797,   168,    14, ...,     0,     0,     0],
       ...,
       [   51,     6,   689, ...,     0,     0,     0],
       [   48,  1015,    15, ...,     0,     0,     0],
       [   41, 18699,   278, ...,     0,     0,     0]], dtype=int64)

In [27]:
batch_X.shape

(16, 1800)

In [28]:
batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [29]:
batch_y.shape

(16, 6)

In [30]:
len(dataset)   #batches --> actual data 9974*16

9974

In [31]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [32]:
int(len(dataset)*.7)

6981

In [33]:
len(train)

6981

In [34]:
len(val)

1994

In [35]:
len(test)

997

In [36]:
train.as_numpy_iterator().next()

(array([[   171, 143787, 192090, ...,      0,      0,      0],
        [  6477,     61,    202, ...,      0,      0,      0],
        [    14,      9,     35, ...,      0,      0,      0],
        ...,
        [   471,     70,     15, ...,      0,      0,      0],
        [    76,     15,    175, ...,      0,      0,      0],
        [     2,  90426,      9, ...,      0,      0,      0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

# 2. Create Sequential Model

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [38]:
model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_FEATURES+1, 32))
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh')))
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# Final layer 
model.add(Dense(6, activation='sigmoid'))

In [39]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirection  (None, 64)                16640     
 al)                                                             
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [ ]:
history = model.fit(train, epochs=2, validation_data=val)

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
plt.figure(figsize=(8,5))
pd.DataFrame(history.history).plot()
plt.show()

# 3. Make Predictions

In [ ]:
input_text = vectorizer('You freaking suck! I am going to hit you.')
input_text

In [ ]:
#we need to pass it as a batch or else it will fail
model.predict(np.array([input_text]))

In [ ]:
model.predict(np.expand_dims(input_text,0))

In [ ]:
batch=test.as_numpy_iterator().next()

In [ ]:
batch_X , batch_Y = test.as_numpy_iterator().next()

In [ ]:
model.predict(batch_X)

In [ ]:
model.predict(batch_X > 0.5)

In [ ]:
(model.predict(batch_X)>0.5).astype(int)

In [ ]:
batch_Y

# 4. Evaluate Model

In [ ]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [ ]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

# 5. Test and Gradio

In [ ]:
pip install gradio jinja2

In [ ]:
import tensorflow as tf


In [ ]:
pip install fsspec==2023.5.0

In [ ]:
#pip uninstall typing_extensions --yes

In [ ]:
#pip uninstall jinja2 --yes

In [ ]:
pip install typing_extensions==4.8.0

In [ ]:
pip install fastapi

In [ ]:
import gradio as gr

In [ ]:
model.save('toxicity.h5')

In [ ]:
model.save('toxicity.keras')

In [ ]:
model = tf.keras.models.load_model('toxicity.keras')

In [ ]:
input_str = vectorizer('hey i freaken hate you!')

In [ ]:
res = model.predict(np.expand_dims(input_str,0))

In [ ]:
res

In [ ]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [ ]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

In [ ]:
interface.launch(share=True)